version: "3.7"

services:
  
  rsx-bank-loans:
    build:
      context: ./server
    image: ee-rsx-kata-bank-loans
    restart: always
    expose:
      - "8080"
    networks:
      - rsx-bank-network 

  rsx-bank-loans-web:
    environment:
      WEB_PORT: ${WEB_PORT:-80}
    build: 
      context: ./ui
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    restart: always
    ports:
      - 0.0.0.0:${WEB_PORT:-80}:80
    networks:
      - rsx-bank-network
    depends_on:
      - rsx-bank-loans


networks:  
  rsx-bank-network: {}

